spring:
  datasource:
    url: ${database.spring.datasource.url}
    username: ${database.username}
    password: ${database.password}
    driver-class-name: ${database.driver}
  jpa:
    database-platform: ${database.platform}
    hibernate:
      ddl-auto: ${database.spring.jpa.hibernate.ddl.auto}
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          "[time_zone]": UTC
          lob:
            "[non_contextual_creation]": true
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  liquibase:
    enabled: ${database.spring.liquibase.enabled}
    change-log: classpath:liquibase/index.xml
  h2:
    console:
      enabled: false
  mail:
    host: smtp.163.com
    username: zdu_20230408001@163.com
    password: INCFTHKUALEWKKTK
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  task:
    scheduling:
      pool:
        size: 50
  threads:
    virtual:
      enabled: true
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
    time-zone: UTC
  lifecycle:
    timeout-per-shutdown-phase: 60s
logging:
  level:
    org:
      hibernate:
        dialect:
          function:
            TemplateRenderer: ERROR
        SQL: OFF
        orm:
          jdbc:
            bind: OFF
        engine:
          jdbc:
            spi:
              SqlExceptionHelper: OFF
server:
  error:
    include-message: always
    include-stacktrace: never
  tomcat:
    max-http-form-post-size: -1
  max-http-request-header-size: 1MB
properties:
  storage:
    root:
      path: default
    cloud:
      aliyun:
        enabled: ${storage.cloud.aliyun.enabled}
        endpoint: ${storage.cloud.aliyun.endpoint}
        bucketName: ${storage.cloud.aliyun.bucketName}
        accessKeyId: ${storage.cloud.aliyun.accessKeyId}
        accessKeySecret: ${storage.cloud.aliyun.accessKeySecret}
  is:
    development:
      mock:
        mode: ${is.development.mock.mode}
